package com.yy.platform.common.model.wonderful;

public class NewNavSubscribe extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_nav_subscribe.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    public NewNavSubscribe(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    public NewNavSubscribe() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_nav_subscribe.uid
     *
     * @return the value of new_nav_subscribe.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_nav_subscribe.uid
     *
     * @param uid the value for new_nav_subscribe.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}