package com.yy.platform.dao.mapper.wonderful;

import com.yy.platform.common.model.wonderful.NewNavSubscribe;
import com.yy.platform.common.model.wonderful.NewNavSubscribeExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

@Mapper
public interface NewNavSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    int countByExample(NewNavSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    int deleteByExample(NewNavSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    @Delete({
        "delete from new_nav_subscribe",
        "where uid = #{uid,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    @Insert({
        "insert into new_nav_subscribe (uid)",
        "values (#{uid,jdbcType=BIGINT})"
    })
    int insert(NewNavSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    int insertSelective(NewNavSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    List<NewNavSubscribe> selectByExample(NewNavSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NewNavSubscribe record, @Param("example") NewNavSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_subscribe
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NewNavSubscribe record, @Param("example") NewNavSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_nav_recommend
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "uid",
            "from new_nav_subscribe",
            "where uid = #{uid,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    NewNavSubscribe selectByPrimaryKey(Long uid);
}